# Main menu
[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "Resume"
  url = "/resume/"
  weight = 2

[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[main]]
  name = "Posts"
  url = "/post/"
  weight = 4

[[main]]
  name = "About"
  url = "/about/"
  weight = 5
